"""
Django settings for ZTInventoryApp project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--$xw1unc_ptpxdpym85impby_*7@1i81*h@mzl8se0456&+hm#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.humanize',
    'channels',
    'ims.apps.ImsConfig',
    'accounts',
    'core',
    'location',
    'application',
    'catalog',
    'vendor',
    'inventory',
    'customer',
    'rest_framework',
    'auditlog',
    'project'
]

MIDDLEWARE = [
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.current_user.CurrentUserMiddleware',
    'ZTInventoryApp.middleware.SessionRedirectMiddleware',
    'auditlog.middleware.AuditlogMiddleware'
    
]

ROOT_URLCONF = 'ZTInventoryApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,  'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'application.context_processors.app_custom_processor'
            ],
        },
    },
]

WSGI_APPLICATION = 'ZTInventoryApp.wsgi.application'
ASGI_APPLICATION = 'ZTInventoryApp.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    },
    'other_db_local': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'D:\project\IMS\db.sqlite3',
    },
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'ims_inventory',  # The name of your database
    #     'USER': 'postgres',       # The username to connect to PostgreSQL
    #     'PASSWORD': 'postgres@123',  # The new password you set
    #     'HOST': '127.0.0.1',     # The host (localhost)
    #     'PORT': '5432',           # The port PostgreSQL is running on
    # },
    'other_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'immdb',
        'USER': 'imm',
        'PASSWORD': 'mspl@2025$^',
        'HOST': '192.168.10.245',
        'PORT': '5433'
    }
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/



STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,  'static'),
    # 'C:/projects/ZTInventoryApp/static',
    # 'C:/Users/Santhosh.Emmadi/Downloads/BootstrapZx/MeslovaInventoryApp/static',
]

# settings.py

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'

SITE_ID = 1


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LOGIN_URL = '/login/'               # Where @login_required redirects unauthenticated users
LOGIN_REDIRECT_URL = '/home/'            # Where users go after login (if no ?next= in URL)


# settings.py

# How long a persistent session lasts (in seconds) — default: 2 weeks
SESSION_COOKIE_AGE = 60 * 60 * 24 

# Expire session when browser closes (useful for "No Remember Me" scenario)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# Refresh expiry on every request — good for active users
SESSION_SAVE_EVERY_REQUEST = True

# Prevent cookie theft via JavaScript
SESSION_COOKIE_HTTPONLY = True

# Force HTTPS for cookies (must have HTTPS enabled)
SESSION_COOKIE_SECURE = True

# Make CSRF cookies secure too
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True


import os, datetime
import logging
from logging.handlers import RotatingFileHandler, TimedRotatingFileHandler

LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOG_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',  # For size-based rotation
            'filename': os.path.join(LOG_DIR, f'django_{datetime.datetime.now().strftime("%Y-%m-%d-%H")}.log'),
            'maxBytes': 5 * 1024 * 1024,  # 5 MB per file
            'backupCount': 7,  # Keep 7 old files
            'formatter': 'verbose',
        },
        'daily_file': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',  # For daily rotation
            'filename': os.path.join(LOG_DIR, 'django_daily.log'),
            'when': 'midnight',  # Rotate every day at midnight
            'interval': 1,
            'backupCount': 7,  # Keep 7 days of logs
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'console': {
            'handlers': ['file', 'daily_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

APPEND_SLASH = True  # Default in Django

USER_DEFAULT_PASSWORD = 'rm#123'

DEFAULT_THEME = 1

# try:
#     from .local_settings import *
# except ImportError:
#     pass
